### ISSUE TITLE
NA's in violin plots

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#101]
@yiwenlu @KenLi93 

I'm seeing an NA category generated now in the violin plots in `cor_graphical`. I think it's probably down to the missing values for `wt`. 

<img width="514" alt="Screen Shot 2021-03-04 at 2 07 33 PM" src="https://user-images.githubusercontent.com/17482713/110016426-00f6bf00-7cf3-11eb-8df3-fccfb972fb5a.png">

**Comment by yiwenlu** [comment]
Hi David,

I just sent a pull request which should be able to fix this.

Yiwen

**Comment by benkeser** [comment]
Resolved by #116
