### ISSUE TITLE
Empty subfolders

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#103]
@cyu-hvtn @Larsvanderlaan @youyifong @yiwenlu @KenLi93 

Just a note that if you save output to a subfolder of `output` or `figs` or `data_clean`, you need to manually upload that folder to GitHub. Do this by placing an empty file named `.gitkeep` in the empty directory and committing the result.

For example, say my code in `cop_mediation` generates a figure that I want to save in `cop_mediation/figs/mediation_graphics`. To submit this code for a PR, I also need to manually create this folder and drop a `.gitkeep` file in it. 

```bash
# create folder
mkdir cop_mediation/figs/mediation_graphics
# empty file in it so git recognizes it
touch cop_mediation/figs/mediation_graphics/.gitkeep
# commit the result
git add cop_mediation/figs/mediation_graphics
git commit -m "add mediation_graphics folder" 
```

@nhejazi or @thebioengineer , could we drop this somewhere in contributing guidelines? It's happened numerous times on PRs.

**Comment by benkeser** [comment]
This is more of an FYI. There's not really a TO-DO at the moment for this, as I've been manually doing this for you. But as soon as we have a stable build on travis, I will not be doing these type of edits for your sub folders and will expect you to fix your PRs so that it does not destroy the stable build.

**Comment by thebioengineer** [comment]
@nhejazi - Making sure you have not done this yet. I think it makes sense to add to contributing guidelines and I can throw it in a branch tonight and open a PR

**Comment by nhejazi** [comment]
I haven’t done this yet — would be great to have it in the guidelines @thebioengineer

**Comment by thebioengineer** [comment]
See #108

**Comment by nhejazi** [comment]
The contribution guidelines have been updated accordingly by merging #108.
