### ISSUE TITLE
build branch

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#104]
@nhejazi @thebioengineer 
Brain storm here -- and it's late in the day, so this might not make sense -- what if we instituted a `build` branch of the repo. The idea is that only Travis would push to this branch after successful builds, but this branch __would__ include derived (binary) output files.

This may be convenient for contributors for pulling derived objects from other folders to confirm that the report builds when they've updated their code. 

Example: I want to update `cop_mediation`, but I don't want to have to re-build all the other `cop` analyses from scratch. So I populate those folder's `output`/`fig` directories from the `build` branch, so that I can quickly compile the report with my own `cop` results, to confirm that the report builds. 

Maybe this is overkill, as I could just specify my own report build command that checks just my report code.

I don't know: any benefit to this? Or am I under-caffeinated?

**Comment by thebioengineer** [comment]
I think that sounds interesting as well. Kind of reminds me of packages that use {pkgdown} to build sites for them automatically would have travis (now gh actions) push to a gh_pages branch.

**Comment by nhejazi** [comment]
I think this could be a useful addition but it adds the overhead of dealing with another deploy step to have Travis push to this extra branch as well as to `gh-pages`.

My proposed implementation of this would be to have Travis copy/push all relevant build artifacts (e.g., in the `figs`, `output`, etc., directories of each of the analysis folders to `gh-pages`, as it does already with the built reports). Then, we could have a “sync” recipe in the Makefile that copies the artifacts hosted by the GitHub pages site to the relevant subdirectories of the analysis folders. This way, I could easily grab the artifacts from, e.g., `cop_mediation` when I’m working on `cop_stochastic` and need to compile the CoP report.

**Comment by benkeser** [comment]
I like that idea, but the `sync` recipe seems like a bit of a headache to write. 

I'm not too worried about the travis pushes, but I don't feel strongly if it's pushing to one branch or two. Probably one is simpler.

**Comment by benkeser** [comment]
I'm going to close this for now, as it doesn't seem high enough priority to warrant an open issue. If creativity sparks in someone, feel free to re-open.
