### ISSUE TITLE
mock data documentation

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#110]
Could we add to `data_clean/README.md` to describe 
- `wt.2` 
- `NA`s in `wt` and `wt.2` and how to interpret

**Comment by youyifong** [comment]
we should bring over the documentation in the old data package and wt.2 can
be added in that.

**Comment by benkeser** [comment]
[Is this it](https://github.com/CoVPN/correlates_reporting/blob/master/data_clean/README.md)

**Comment by youyifong** [comment]
Yes, that's it. I will edit this file.

**Comment by benkeser** [comment]
Resolved by #111
