### ISSUE TITLE
automated code checks via precommit

### ISSUE THREAD

**Issue by nhejazi** [CoVPN/correlates_reporting#121]
In order to reduce the potential of introducing erroneous code and to enforce uniformity in code style, we should adopt the pre-commit framework. By adding a simple configuration file and installing the pre-commit package, we can run automatic checks that ensure R code is valid, correctly styled (via the `styler` package), and more — all prior to commits being made. More at https://lorenzwalthert.github.io/precommit/articles/available-hooks.html. Worth getting this set up @benkeser @thebioengineer? If so, I can take an initial pass at it.

**Comment by benkeser** [comment]
I wouldn't put it high on the priority list personally, but if you want to look into it, go for it.

**Comment by benkeser** [comment]
Closing until @nhejazi feels inspired.
