### ISSUE TITLE
removing imagemagick dependencies

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#123]
@nhejazi @Larsvanderlaan 

Getting the threshold report to build on travis was proving to be quite a pain; around a46d530, I started noticing that the table files rendered to `pdf` were not being generated. It seems to be an issue with needing to [configure kableExtra](https://haozhu233.github.io/kableExtra/save_kable_and_as_image.html). This all just seemed like too much, so I moved away from that structure in 13ded38 to have the `kable` tables generated as `latex` output directly in `sub_report.Rmd`. It seems to be building on `travis` now, but waiting for the full build to confirm.

ALL THAT SAID: can we now remove the `imagemagick` libraries and dependencies? @Larsvanderlaan is this used anywhere else in your code? It'd be nice to get rid of it to speed up automatic builds.

**Comment by nhejazi** [comment]
It looks like #114 successfully built, so could we just check this by removing the `imagemagick` dependency and seeing what happens with the build?

**Comment by Larsvanderlaan** [comment]
Hi David,
I cannot thank you enough for the work you have put into merging my code. 
The only places where I used kable/kableExtra were the places you changed. I have sent a pull request removing the "library(magick)" and "library(kableExtra)" calls.
