### ISSUE TITLE
issues with RCDF plots

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#126]
- `NA`s present
- text in legend cut off
- Also, what does o: and e: mean in the legend?

<img width="748" alt="Screen Shot 2021-03-07 at 12 08 43 AM" src="https://user-images.githubusercontent.com/17482713/110229708-745a2580-7ed9-11eb-8c13-f62b56f483b0.png">

**Comment by KenLi93** [comment]
Hi David and Nima,

Thank you for reporting this error! In cohort_event variable there were NAs for subjects with Perprotocol == 0. I will exclude such subjects in the next PR. I will also fix the problem with the legend. The letters o: and e: are supposed to be "placebo" and "vaccine"

**Comment by benkeser** [comment]
Resolved by #135
