### ISSUE TITLE
more transparency in spaghetti plots

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#127]
<img width="716" alt="Screen Shot 2021-03-07 at 12 11 33 AM" src="https://user-images.githubusercontent.com/17482713/110229756-b7b49400-7ed9-11eb-84ca-bfe0d94e0856.png">

**Comment by nhejazi** [comment]
These are very had to read. In addition to turning the `alpha` low (maybe `alpha = 0.5`), could we make the lines dashed or dotted?

**Comment by benkeser** [comment]
There are lingering issues with transparency even after #135 

<img width="626" alt="Screen Shot 2021-03-08 at 3 55 31 PM" src="https://user-images.githubusercontent.com/17482713/110380908-c361a100-8026-11eb-9263-f121a1f7dd3a.png">

**Comment by benkeser** [comment]
Sorry, was looking at old build

**Comment by benkeser** [comment]
@KenLi93 I see this is now resolved by #135 in cor report, but not immuno

**Comment by benkeser** [comment]
Resolved by #137
