### ISSUE TITLE
Long build times on travis

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#163]
> Travis seems to enforce a 10 min limit. Is that new?

That's always been the case. We've had, at times, to request that code print messages providing status updates so that the builds continue.

I think we need to go back to the travis build logs and git diffs to see what changes may have caused this.

_Originally posted by @benkeser in https://github.com/CoVPN/correlates_reporting/issues/158#issuecomment-806255680_

**Comment by nhejazi** [comment]
We can circumvent the limit of 10min via `travis_wait X`, which will print to the log every minute for X minutes. I’ve tried this in #158, setting X up to 120.

The Travis build itself has a time limit of 2 hours, so I’ve also, at times, disabled the immunogenicity report builds in #158. Builds with just the CoR report take as long as 2 hours and time out the build job.

**Comment by benkeser** [comment]
It seems we're getting clean builds again in under the time allotted. Is this issue resolved?

**Comment by nhejazi** [comment]
This was due to improperly configuring the number of bootstraps and permutations in `cor_coxph/code/params.R`. This was fixed by 23bb07a.
