### ISSUE TITLE
parameters defined in immuno_tabular

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#184]
@cyu-hvtn 

The variable `labels.assays.short` is defined both in [`_common.R`](https://github.com/CoVPN/correlates_reporting/blob/9e130821a6228738bbd99efe3d72dce1dca31c5e/_common.R#L84), as well as in [`immuno_tabular/code/make_parameters.R`](https://github.com/CoVPN/correlates_reporting/blob/9e130821a6228738bbd99efe3d72dce1dca31c5e/immuno_tabular/code/make_parameters.R#L187). 

Is this redundancy needed? Could we stick to the version used in `_common.R`? Or does it need to be re-defined here for some reason?

**Comment by benkeser** [comment]
I went ahead and moved some of these definitions over to `_common.R`.  Checking build now.

The only remaining issue is that [your definition of `labels.assays.long`](https://github.com/CoVPN/correlates_reporting/blob/f1aa7f4684192cb928bbe3e4a0c290370331249a/immuno_tabular/code/make_parameters.R#L183) seems to be different than what's in [`_common.R`](https://github.com/CoVPN/correlates_reporting/blob/f1aa7f4684192cb928bbe3e4a0c290370331249a/_common.R#L135).

You seem to be using the short names of assays in your version, where the version in `_common` uses the long names. 

It's fine from my perspective to do this, but just wanted to make sure that is what is expected/desired of the code.

**Comment by cyu-hvtn** [comment]
labels.assays.short in _common.R doesn't include the "anti-N antibody" marker. I first redefine to include all markers, then they were selected based on `assays` and `include_bindN` from _common.R at #L199 https://github.com/CoVPN/correlates_reporting/blob/9e130821a6228738bbd99efe3d72dce1dca31c5e/immuno_tabular/code/make_parameters.R#L199

**Comment by benkeser** [comment]
Yes, but I am referring to `labels.assays.long`

**Comment by cyu-hvtn** [comment]
Oh sorry I misread! I'm using long names too, pasting short names with the time labels

**Comment by benkeser** [comment]
Ok that's fine for now. It just overwrites a variable by the same name read in from `_common.R`. I added a comment indicating as such for posterity.
