### ISSUE TITLE
>= rendering in forest plots

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#185]
Reviewing `_common.R`, I see the variables [`Bstratum.labels` and `demo.stratum.labels` defined](https://github.com/CoVPN/correlates_reporting/blob/9e130821a6228738bbd99efe3d72dce1dca31c5e/_common.R#L89).

I do not see these variables referenced anywhere except for @youyifong 's forest plots. Could we wrap these in a call to `expression()` so that they render as the mathematical symbol in the plots rather than `>=`?

**Comment by youyifong** [comment]
I tried to do this. It is surprisingly difficult. The labels become part of
a table of text that gets passed to the forestplot package (
https://cran.r-project.org/web/packages/forestplot/index.html) and I got an
error saying:

Error in eval(txt_out) : object 'Age' not found

**Comment by benkeser** [comment]
Did you try [this](https://cran.r-project.org/web/packages/forestplot/vignettes/forestplot.html#using-expressions)?

**Comment by youyifong** [comment]
yea

**Comment by benkeser** [comment]
Interesting. I have no problem rendering expressions in `forestplot` on my machine. E.g., 

It seems like the error you are getting is from `R` trying to evaluate the expression `Age`, so maybe it's just quotes that are needed. 

Have you tried formatting as 
```r
expression("Age " >= " 65")
```

or perhaps if you're making a table as
```r
"expression('Age ' >= ' 65')"
```
?

**Comment by youyifong** [comment]
The labels do not get passed directly to forestplot. Erika Rudnicki helped
write a function to make the plot. It is in cor_coxph.R line 305. I
modified her code to try to get it to work, but it was not enough.

**Comment by benkeser** [comment]
Solution in #191
