### ISSUE TITLE
`renv` creep

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#186]
I suspect that we have consider creep of the `renv` libraries needed for this project. It might be a good idea at some point to provision a fresh set of `renv` libraries to reduce the burden of activating `renv`.

**Comment by benkeser** [comment]
Removing dependence on `sass` at least would be desirable as `C++` options needed to install this package conflict with those needed to install `kyotil`.

**Comment by nhejazi** [comment]
Could you say a bit more about this @benkeser? I updated the `renv` library to the most recent version of all packages in #182, but this seems to suggest that there are conflicting non-`R` dependencies.

**Comment by benkeser** [comment]
Not conflicting. Just there are more packages in the lock file than are strictly used by the code at this point.

**Comment by nhejazi** [comment]
We could try to have `renv` regenerate the lockfile by removing/re-initializing the `renv` virtual environment, but this shouldn't be necessary. My understanding is that `renv::dependencies()` scrapes all parts of the repo and builds the dependency list from packages it finds. It also does tag packages for removal from the lockfile when `renv::status()` is run (and updates the lockfile upon calling `renv::snapshot()`).

**Comment by benkeser** [comment]
Ok let's revisit after this week.

**Comment by benkeser** [comment]
Closing for now, since apparently `renv` handles all this.
