### ISSUE TITLE
page numbers off in TOC

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#195]
???

Is it a need to run pdflatex multiple times thing?

Googling did not turn up much...

**Comment by nhejazi** [comment]
Maybe related, https://github.com/rstudio/bookdown/issues/708, but this might be more work than it's worth to track down / fix. Do we need the ToC?

**Comment by benkeser** [comment]
A clickable TOC is nice. 

I can't turn up any info on this sort of behavior. Probably, we'd have to save the `tex` of a build and stare at that to see what's going on.

**Comment by nhejazi** [comment]
Sure, we can just add `keep_tex: yes` to the format specs in `_output.yml` to preserve the TeX files

**Comment by nhejazi** [comment]
Another idea would be to maybe suppress page numbers in the ToC. Since the convenience comes from having a clickable ToC, I don’t quite see why anyone would actually care about the page numbers

**Comment by benkeser** [comment]
But the links also weren’t taking to correct pages.

**Comment by benkeser** [comment]
The page number issue with TOC can be resolved by running `pdflatex` on the `tex` document __three times__ as described [here](https://tex.stackexchange.com/questions/120847/wrong-page-numbering-in-the-table-of-contents-of-figures-and-of-tables). 

__Proposed solution__
- add `keep_tex: true` to `_bookdown_*.yml`
- modify `_build.sh` to:
  - `render_book` (I *think* this will call `pdflatex` twice)
  - add && `pdflatex _report_$1/*.tex` after call to `Rscript`

**Comment by benkeser** [comment]
> Is it a need to run pdflatex multiple times thing?

Answer, it turns out, yes.

**Comment by benkeser** [comment]
> **Proposed solution**

@nhejazi Do you want me to submit a separate PR for this or integrate into #193 ?

**Comment by nhejazi** [comment]
Let’s just integrate this into #193. Feel free to push or lmk and I can alter the relevant build scripts

**Comment by nhejazi** [comment]
Have we verified that this is resolved by 0a0222e? If so, let's mark this as resolved by #194 and not introduce the redundant change in #193

**Comment by benkeser** [comment]
No, still build errors to resolve.

**Comment by benkeser** [comment]
Well, this was a huge pain in the ass to figure out. Crawling out of a very deep rabbit hole. d38f829f2ff98185750de0f2189dbd19742f2358 seems to address this at least locally for me.

**Comment by benkeser** [comment]
Fixed in #194
