### ISSUE TITLE
cor report with only subset of assays

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#196]
I am just wrapping up #194, which allows the immuno report to build for any subset of `assays` and days (29/57).

It seems that our first analyses may not include all four assays and possibly only Day 57 markers, so I'd like to get our code to a place where it can run without requiring this.

@yiwenlu `cor_graphical` currently breaks (see [line 6008 here](https://travis-ci.com/github/CoVPN/correlates_reporting/builds/221453996)). 

I haven't run through @youyifong 's `cor_coxph` nor @Larsvanderlaan `cor_threshold`. If time this week, would be good to have PRs submitted as needed for all of these directories.

**Comment by benkeser** [comment]
@youyifong @thebioengineer A note that if `times` is changed in `_common.R` e.g., `times <- c("B", "Day57")`, the [initial data processing script breaks](https://travis-ci.com/github/CoVPN/correlates_reporting/builds/221502155).

**Comment by youyifong** [comment]
It is a rather massive change ...

**Comment by benkeser** [comment]
Yes, perhaps nothing needs to happen immediately, but it may be desirable to start addressing the issue soon, since we know JnJ will not have Day29 and Day57. 

Right now, if we only have data on Day57 markers (seems likely for Moderna initial run), we will need to arbitrarily fill in `Day29` markers so that the code runs. That's fine; we can still get results, but it increases build time unnecessarily and results in a somewhat confusing report with duplicated results etc.

**Comment by youyifong** [comment]
Good point. I am going to submit a new PR with a new data processing
script.

Elllis, I also checked in a new spec and will send you a link to the new
processed data.

Best,
Youyi

**Comment by thebioengineer** [comment]
Thanks for the heads up. Send me the new data to be verified against when you get a chance!

**Comment by yiwenlu** [comment]
@yiwenlu `cor_graphical` currently breaks (see [line 6008 here]

@benkeser Could you help test if this is still breaking? I have tried many times but it works on my machine.

**Comment by benkeser** [comment]
What specific settings in `_common.R` are you wanting to check?

**Comment by benkeser** [comment]
> What specific settings in `_common.R` are you wanting to check?

Just open a PR with `_common.R` changed to a subset of `assays` and either `Day29` or `Day57` only. That will trigger a build and we can see if it works or not.
