### ISSUE TITLE
formatting of risk score report

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#210]
A few minor formatting comments on the risk score report:
- There is inconsistency in the way super learner is written -- at times it's superlearner, Superlearner, or SuperLearner. Can we pick one form of spacing/capitalization and apply uniformly throughout report?
- Figure 1.1 
  - could we write in words what `EventIndPrimaryD57` means in the figure title instead of referencing the variable name?
  - The caption in general is a bit too long here. What about something like "Cross-validated AUC (95% CI) of algorithms for predicting COVID-19 disease status starting X days after Day 57"? (I can't remember offhand what X should be)
  - Increase text size in figure for everything (labels, ticks, etc)
  - May also wish to increase point size
  - Possible to add vertical grid lines as well?
- Figure 1.2
  - Change caption to "Predicted probabilities of COVID disease X days after Day 57 by case/control status for top 2 learners, SuperLearner and Discrete SL."
  - In previous comment, adhere to chosen capitalization scheme of "super learner"
  - Increase text size
  - Are these in placebo recipients or vaccine recipients?
- Figure 1.3
  - capitalization of super learner
  - Increase axis label and legend font size
- Table 1.3
  -  SL.Weights => Weight
  - Remove "(risk score analysis)" from caption
- Table 1.4
  - The font looks funny on this table
  - Remove "(risk score analysis)" from caption

**Comment by brborate** [comment]
@benkeser Am working on this. Will update shortly.

**Comment by benkeser** [comment]
> they are on the placebo recipients.

Is it worth making a similar figure for SL predictions in vaccine recipients? Might be nice to see the distribution of the risk score used in the downstream analyses.
