### ISSUE TITLE
integrating risk scores into CoR methods

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#211]
@nhejazi @brborate, could you provide @youyifong and @Larsvanderlaan an overview of where and how the risk scores are saved after they've been calculated? We'll then look for PRs with updates to `cor_coxph` and `cor_threshold` that adjust for these risk scores.

**Comment by nhejazi** [comment]
Upon a successful run, the baseline  risk score workflow adds a new file to the top level `data_clean` directory: https://github.com/CoVPN/correlates_reporting/blob/master/base_riskscore/code/append_risk_score_to_data.R

in the CoR (and CoP) analyses, it should be sufficient to still use the `data_name` variable exported by `_common.R`, loading instead a version of the file with the string “_with_riskscore” appended to the end of the file name. This CSV file is exactly the same as the cleaned data but contains an additional column `risk_score` to be used in accounting for exposure.

**Comment by brborate** [comment]
Thanks Nima, this appending to the CSV file in the data_clean directory looks great!

**Comment by youyifong** [comment]
Thanks. Is there a make command to produce the data file with riskscore?
Youyi

**Comment by benkeser** [comment]
`make risk_analysis`

**Comment by youyifong** [comment]
I refreshed again and see it now. Thanks.

**Comment by youyifong** [comment]
I am getting this error when I do "make risk_analysis". Any ideas?

In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file
'.../correlates_reporting/base_riskscore/output/objects_for_running_SL.rda',
 probable reason 'No such file or directory'
Execution halted

**Comment by brborate** [comment]
It seems "make risk_analysis" is not setting the "make all" within base_riskscore to action as expected.

**Comment by benkeser** [comment]
Could it be because the `Makefile` does not specify dependencies between components of the analysis? @brborate, do you have certain recipes that rely on the output of other recipes? If so, they should be added after `:` in the `Makefile` to make sure things execute in the proper order. It might compile on your machine because you already have some output saved locally.

**Comment by brborate** [comment]
@benkeser @youyifong  I checked details and I have no output saved locally. Re-running from scratch still is working at my end. 

Youyi: Do you want to chat over a Slack call today evening (9 PM) or tomorrow morning (say 9 AM)?  

Best, 

Bhavesh

**Comment by brborate** [comment]
Hi @nhejazi, Youyi and I will be chatting tomorrow at 11.30 AM. Are you available during this time?

**Comment by nhejazi** [comment]
Got it, I would be free 1130a-12p tomorrow so I can try to join you during that window.

**Comment by benkeser** [comment]
Completed with #241
