### ISSUE TITLE
cleaning out `gh-pages` branch

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#214]
At some point, we probably want to delete/re-initiate `gh-pages`. `clone`ing the repo is getting quite slow. I think from all the large diffs induced by the pdfs on that branch.

@nhejazi @thebioengineer any ideas on this? Just manually delete and then re-open an empty branch by the same name?

**Comment by benkeser** [comment]
Just make it more complex instruction-wise to access. I'm fine with it though if that's what we want to do.

**Comment by nhejazi** [comment]
I think we should just have a "How to clone" statement in the README. That way, anyone can just clone by copying the line anyway, even if unfamiliar with Git / version control.

**Comment by benkeser** [comment]
Sounds good. And also include in `aws_build_instructions.md`

**Comment by benkeser** [comment]
I suggest that we actually do this (remove entire branch) after Moderna real report is complete. `git pull`'s are getting a little unseemly. Doesn't seem much downside to losing the diffs for pdfs.

**Comment by nhejazi** [comment]
Ok, that sounds fine to me, especially since we're just losing drafts of mock reports. Good to re-generate now that the analyses have hit a point closer to stability.

**Comment by benkeser** [comment]
Cleaned out and a new orphan branch `gh-pages` added.
