### ISSUE TITLE
sl verification mismatch

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#216]
I am getting a match on risk scores with the verification code, but no longer am matching on CV-AUCs. 

We previously had a match on CV-AUCs and my code for this part hasn't changed. The most likely explanation seems to be a discrepancy in random seed being set. I wonder if this changed when @nhejazi integrated the code into the main repo? @brborate and @nhejazi, could you take a look at the specs and the code and confirm that they align?

**Comment by nhejazi** [comment]
You're right about a difference being introduced with setting the random seed. Prior to some recent changes, the code prior to the CV-AUC calculation explicitly had a call `set.seed(20210216)`, which I removed. That same seed is explicitly set (via `set.seed` in @brborate's code and via the `seed` argument of `mice` in your code), so upstream processing like imputation remains the same. Reintroducing that `set.seed` call in the appropriate part of @brborate's code should fix this.

**Comment by nhejazi** [comment]
@brborate Would you mind adding `set.seed(20210216)` before this line (https://github.com/CoVPN/correlates_reporting/blob/master/base_riskscore/code/run_cvsl_riskscore.R#L112) in your forthcoming PR to resolve other issues related to the baseline risk score code? Once this has been re-added, @benkeser should be good to re-run his verification code.

**Comment by brborate** [comment]
Thanks Nima and David, ya this should fix it, I think too.

**Comment by benkeser** [comment]
I thought in the specs that there were different seeds set prior to the CV SL run. So I'll just let @brborate let me know how he wants to proceed. Previously, when we were using 10 seeds, we generated those seeds randomly and set them prior to call to CV SL. But now we are just running CV SL once, so maybe we can simplify.

**Comment by brborate** [comment]
I have added the seed before running CV SL.  👍

**Comment by benkeser** [comment]
So prior to the call to `CV.SuperLearner` you are setting seed 20210216?

**Comment by brborate** [comment]
that's correct. Though I see we are not running CV SL with any random seed as we are running it only once, but I wonder if this takes care of any randomness occurring within CV SL function itself.

**Comment by benkeser** [comment]
As long as we set the same seed prior to the run. And as long as our algorithms in the library are coded in the same order (they are), we should be OK.

**Comment by nhejazi** [comment]
Setting of the seed was competed in #222 so if you’re good to re-check the verification code than we can close this @benkeser

**Comment by benkeser** [comment]
resolved in #51
