### ISSUE TITLE
bug in cor_tabular

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#218]
Moderna reports a bug in `cor_tabular` code.

![image](https://user-images.githubusercontent.com/17482713/113129683-2fc85e00-91e9-11eb-934a-4c9c5ea402e0.png)

**Comment by benkeser** [comment]
@cyu-hvtn, could you confirm that #225 will eventually fix this?

**Comment by cyu-hvtn** [comment]
Yes

**Comment by benkeser** [comment]
Any updates on this?

**Comment by cyu-hvtn** [comment]
Almost done! Made some other updates too

**Comment by benkeser** [comment]
Fixed in #225
