### ISSUE TITLE
noting commit hash in report

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#277]
@nhejazi @thebioengineer what do you think of the idea of adding an appendix or something to report with the commit hash of the repo that was used to create the report?

I think this may prove useful for us as we start to work on multiple studies and are generating multiple reports.

**Comment by thebioengineer** [comment]
Oh, like as a footnote or just at the end of the report?

**Comment by benkeser** [comment]
Exactly.

**Comment by benkeser** [comment]
Don't know all those words, but sounds good. Are there privacy concerns there?

**Comment by thebioengineer** [comment]
I think as another check, run `digest::digest(file = here("data_raw",data_in_file )` and `digest::digest(file = here("data_clean",data_name)` - then we can always verify that the data as it exists in `data_clean` and `data_raw` are the data used to generate the report

**Comment by thebioengineer** [comment]
as far as I am aware, all the hash is is a unique identifier for the contents of the file, but cannot be used to regenerate the data - I would double check that statement though.

**Comment by benkeser** [comment]
You want to volunteer to tackle this?

**Comment by thebioengineer** [comment]
I can put some code together, but might need to work with you to get it into the report as an appendix

**Comment by benkeser** [comment]
Maybe better as a footnote on the title page of the report. Maybe @nhejazi could help figure that out?

**Comment by thebioengineer** [comment]
First attempt is currently an appendix in [this run](https://github.com/CoVPN/correlates_reporting/commit/499a122e71f2bfaab14ff489a78d9d6b6ea1c619) in the `covpn_correlates_cor.pdf`. Is what you were thinking? or more of a table?

**Comment by benkeser** [comment]
Thanks @thebioengineer and @nhejazi for awesome work on #282
