### ISSUE TITLE
Will we allow `NA` in event indicators?

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#308]
What was the resolution on this @youyifong? Can we update docs and tests accordingly? And make sure everyone is aware of the decision.

**Comment by youyifong** [comment]
How do I add file changes to a PR? I use a github gui. Should I just create
a new PR?

**Comment by benkeser** [comment]
Not sure what you mean? What are file changes vs. commits?

**Comment by youyifong** [comment]
They are the same thing. Is PR308 opened for the purpose of making changes
to the data check?

**Comment by benkeser** [comment]
This is an issue thread, not a PR. Sorry for the confusion.

**Comment by youyifong** [comment]
I see. Sorry. I will open a new PR.
