### ISSUE TITLE
Table 4s and 5s of immuno tables

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#329]
From Peter:
All table 4s and all tables 5s: Extend the footnote to include one more sentence: “LLOQ = 0.48, 5.43, 1.80 IU/ml for N, RBD, Spike, respectively.”

Currently, the LLOQs are the old ones, not the updated ones, I wonder if the code is not ‘seeing’ the updates in common.R?

**Comment by cyu-hvtn** [comment]
Hi David, this issue and #328 have been implemented in the last PR #325 and merged to the master branch. Thanks!
