### ISSUE TITLE
Immuno graphical changes

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#330]
From Peter:
For the arrangement of 5 panels in Fig 2.51 through 2.66, can the 3 bAb readouts be put in the same row or column, and the two pseudovirus nAb readouts put in the same row or column? (as units of assays)

@KenLi93, was this resolved by #324?

**Comment by benkeser** [comment]
I see that it was. Thanks!

**Comment by KenLi93** [comment]
Thank you, David!
