### ISSUE TITLE
cor graphical changes

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#332]
- [ ] Labeling in many figures (axis labels, figure legends, facet titles).  “PP Cases” and “PP Non-Cases” is not the correct terminology anymore (following the README).  It should now be “Primary Cases” and “Non-Cases”.  Search and replace labeling on this issue.
- [ ] Section 2.5 violin and line plots: Try to increase the font size of the LLOD text, and of the proportions at the top of the plots?  When these plots are put into slides, it will be hard to read those proportions.

**Comment by KenLi93** [comment]
Hi David,

I am working with Yiwen to address Peter's comments. I believe Yiwen with
submit the updates shortly.

Best regards,
Kendrick
