### ISSUE TITLE
PR builds not always pushed

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#354]
These lines are now commented out in `_deploy_reports.sh`
````
# NOTE: the following is incompatible with simultaneous Travis jobs that post
#       individual reports independently
#git rm -rf *
#echo "Remaining files in correlates_reporting/ after git rm:"
#ls -l
````

But it seems that sometimes reports on `gh-pages` are not updated after successful builds. E.g, [this build](https://travis-ci.com/github/CoVPN/correlates_reporting/builds/227628869). The message on travis from git is nothing new to commit.

Trying to force (`-rf`) copying on #352 to see if that solves it.

**Comment by benkeser** [comment]
@nhejazi could you take a look at this please?

**Comment by benkeser** [comment]
@thebioengineer, I can't find Nima. Any chance you have bandwidth to take a look at this?

**Comment by thebioengineer** [comment]
Lets poke around - its kind of hard because the logic looks like it should be updating and it looks like everything ran. Git just doesn't think there were any changes

Opening a PR #363 to print out all the files

**Comment by nhejazi** [comment]
I'm not quite sure (yet) what exactly is going on but the information provided by `git` doesn't make too much sense: Consider the lines below https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/510537381#L12178, where the PDF reports before/after copying are somehow exactly identical --- all generated/updated by travis with modification dates matching today's date, yet the reports on `gh-pages` were last updated 6 days ago (!)

**Comment by nhejazi** [comment]
The last PR to result in a successful push to `gh-pages` apparently was https://github.com/CoVPN/correlates_reporting/pull/340. As of the next PR's commits, we see https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/507841153#L19792, "No anonymous write access", which is continued in the next 4-6 PRs, at which point the current behavior appears in https://github.com/CoVPN/correlates_reporting/pull/344 (https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/508715158#L21250). I think the main issue is as indicated above --- why are the PDF files exactly the same before _and_ after copying? As in, why are the updated PDF files available prior to the force copy on the cloned `gh-pages` branch?

**Comment by nhejazi** [comment]
OK, at least one mistake is in the syntax for specifying environment variables for Travis to export. The environment variable `REPORT_TYPE` is not being exported at all since the newly introduced `TRIAL` env var is issued by duplicating the `env` key. This is fixed in 96625c3.

**Comment by benkeser** [comment]
Good catch. I did this 😳

the if statement in deploy script must not be getting hit.

**Comment by nhejazi** [comment]
...and we're back! :rocket:
