### ISSUE TITLE
`renv/activate.R` changes

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#357]
This file changes a lot and it's sort of annoying to manage on PRs. Doesn't really seem to break anything, but do we understand the source of the changes? Different local package versions or what?

**Comment by thebioengineer** [comment]
If I had to guess, it is due to local {renv} versions 🤷

**Comment by nhejazi** [comment]
The changes are likely just due to differences in styling defaults on individual machines. The `renv` version should itself be controlled by the lockfile.
