### ISSUE TITLE
cor nonlinear chapter titles

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#366]
<img width="853" alt="Screen Shot 2021-06-03 at 11 25 49 AM" src="https://user-images.githubusercontent.com/17482713/120670516-7d1db180-c45e-11eb-8ee9-2bf1a897d3bd.png">

Currently, Day 29 analyses for non-linear CoR are labeled as Day 57 in the section headings.

**Comment by youyifong** [comment]
Thanks for catching this. PR 370 provides a fix.
