### ISSUE TITLE
positivity call

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#368]
From Peter:

VRC has advised that we should define positive response for the bAb markers based on new positivity cutoffs.  Revised text in the SAP: “For each binding antibody marker, the estimated percentage of participants defined as responders, and with concentrations $\ge$ 2x LLOQ or $\ge$ 4 x LLOQ, will be provided with the corresponding 95\% CIs using the Clopper-Pearson method.  A positive response for bAb Spike, bAb RBD, and bAb N is defined as concentration above 10.8424, above 14.0858, and above 23.4711, respectively, on the IU/ml scale.” “As noted above, binding antibody responders at each pre-defined timepoint are defined as participants with concentration above the specified positivity cut-off, with a separate cut-off for each antigen Spike, RBD, N (10.8424, 14.0858, and 23.4711, respectively, in IU/ml).”
 
I think comment 3 only impacts Chenchen / Yiwen’s tabular output, where the code is the same except the positive response rule is changed to use of the positivity cutoff (so LLOQ is not used anymore for positive response).  Note LLOQ is still used for 2FR and 4FR, in the same way as specified before.

@cyu-hvtn @yiwenlu, please confirm whether this code has been added.

**Comment by yiwenlu** [comment]
@benkeser I just submitted a PR for positivity call changes in my CoR figures, and have requested Di's verification for them. I will verify Chenchen's immuno/CoR tables again after she make this change and send me her updates.
