### ISSUE TITLE
ULOQ in immuno reports

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#369]
From Peter:
The new immunogenicity reports will NOT use ULOQ values, they will show all values regardless of whether above the ULOQ.  So our mock immunogenicity reporting should not use ULOQs.  Our correlates reports do use the ULOQs.

@cyu-hvtn @yiwenlu @KenLi93, could you please confirm that immuno reporting conforms to the above

**Comment by KenLi93** [comment]
Hi David,

Thank you for this update! Currently, in the immunogenicity plot, I draw the ULOQ lines for the applicable graphs. Did you mean that the ULOQ values will not be used at all and those lines should be removed?

**Comment by cyu-hvtn** [comment]
Yes, Immuno doesn't use ULOQs and CoR does.

**Comment by benkeser** [comment]
@KenLi93, I think it’s just that the markers are not truncated at ULOQ. Showing ULOQ on graph seems OK.

**Comment by KenLi93** [comment]
@cyu-hvtn @benkeser Thank you both for the clarification!

**Comment by benkeser** [comment]
So Ok to close this issue then?

**Comment by KenLi93** [comment]
There should be no issues on my end if it's okay to keep ULOQ lines in the plots.

**Comment by yiwenlu** [comment]
@benkeser I can confirm immuno (verification for table) doesn't use ULOQs and CoR (verification for table and CoR figures) does.
