### ISSUE TITLE
table numbers

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#379]
Desired to have Tables by labeled as `Table X.Y` where `X` is the chapter of the report and `Y` is the number within that section.

This might help?
https://community.rstudio.com/t/pdf-table-captions-dont-use-section-subsection/27643

**Comment by benkeser** [comment]
I think labels are being dropped because of [this line](https://github.com/CoVPN/correlates_reporting/blob/c8fec9fc60cedd5793a2d6d2bb09848dc5fe85da/cor_tabular/report.Rmd#L11)

Is this OK for me to remove?

**Comment by benkeser** [comment]
It looks like [this line](https://github.com/CoVPN/correlates_reporting/blob/c8fec9fc60cedd5793a2d6d2bb09848dc5fe85da/cor_tabular/report.Rmd#L72) manually generates table labels as well? Can we remove the manual numbering of tables and let latex handle it?

**Comment by benkeser** [comment]
See suggested modifications in #381

**Comment by cyu-hvtn** [comment]
The title will be messy if that line is removed. But I can add a line to restore the default option after running my code

**Comment by cyu-hvtn** [comment]
The line to reset the table label format has been added to #377
