### ISSUE TITLE
Handling PRs in the multiple study era

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#402]
PR #398 adds lines to `.travis.yml` that trigger builds of the pooled Janssen analysis.

I am suggesting that we go ahead and merge this PR so that we can start handling PRs for ENSEMBLE code. However, PRs for code updates that pertain to Moderna may still show ENSEMBLE builds breaking and therefore testing failing. 

I guess the question is at what point do we allow PR's to be merged while still failing ENSEMBLE builds? Anyone have thoughts?

**Comment by thebioengineer** [comment]
could we have whomever opens the PR somehow tag that it is either for moderna or ENSEMBL, and run the code accordingly?

**Comment by benkeser** [comment]
Agree that’s ideal. Not sure if do-able on Travis.

**Comment by youyifong** [comment]
I looked at some of the build errors. They seem fixable. I am in favor of
not skipping the travis build test requirement for extending the code to
work with the ensemble data.

**Comment by benkeser** [comment]
Maybe we should just integrate testing for ensemble piecemeal. Eg first just run a test of the data clean. Then add test of immuno/cor reports when that code is ready?

**Comment by youyifong** [comment]
I think I did not understand the situation before, sorry. I guess as long
as it is temporary, it should be fine.

Would it be possible for several of us to submit changes to PR 398 to get
it to a state that does not fail?

The incremental change sounds good if that is doable and not too
labor-intensive.

**Comment by benkeser** [comment]
Following up on this -- 
In the most recent commit in #398, I have defined a travis job that just processes the ensemble data (i.e., runs `make data_processed` with `TRIAL=janssen_pooled_mock`. If that passes, I'll go ahead and merge.

Then my suggestion for next step is to create an `ensemble_immuno` branch, where the travis build will have an automated build for the Janssen pooled immuno report turned on for this branch. PRs can be submitted to this branch to test builds on travis. Once the immuno report build completes successfully, we'll merge into master.

Does that sounds OK?

**Comment by youyifong** [comment]
Sounds good to me. Thanks.
