### ISSUE TITLE
Optimal surrogate pushes build over run time limit

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#414]
Current builds of correlates report time out with the addition of the optimal surrogate analysis. I see two ways forward:

1. Trigger an additional build of just the optimal surrogate report on travis (assuming the total run time is <120 minutes)
2. Add a (default) reduced library so that the code executes in a shorter amount of time. 

@brborate, any thoughts?

**Comment by brborate** [comment]
Hi @benkeser, I can create a default reduced library the way we had done for baseline risk report earlier. Working on it now, and will push in some time.
