### ISSUE TITLE
cor_surrogates output

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#433]
Is it possible to reduce the amount of output generated by the surrogates analysis. It's currently making travis logs quite difficult to read. One idea would be to turn `verbose = FALSE` to all calls to super learner. It also looks from the output as though one of the screeners may be printing out information each iteration (e.g., [here](https://travis-ci.com/github/CoVPN/correlates_reporting/jobs/522636749#L61871)). Could that be turned off?

**Comment by brborate** [comment]
Agree, will do this.

**Comment by benkeser** [comment]
Perhaps just a message printing which variable set is being run before the call to `SuperLearner` should be sufficient?

**Comment by benkeser** [comment]
Resolved in #442
