### ISSUE TITLE
reducing build time of immuno graphics

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#435]
Going forward it will be useful to work towards reducing the build time of reports so that travis builds execute more quickly (since we've burned through all our free build hours).

@brianSimpkins, it would be useful as you start to dig through the code and work on modifications to consider whether/how the build times could be reduced for the mock reports. E.g., for each class of figure, perhaps a "fast build" would only include a subset of graphics (e.g., only a figure in one stratum vs. all strata).

I do not know @KenLi93's code well enough to know how easy this would be, but if it's reasonably straightforward to implement such a check, it might be useful. Let me know what you think.

**Comment by brianSimpkins** [comment]
It should be relatively straightforward to work on this. At the least I can keep the code from producing any figures that aren't going to be included in the final report. I'll see what I can do and push any changes ASAP.

**Comment by benkeser** [comment]
This should not be a priority at the moment (we need ENSEMBLE immuno results asap, this can wait), but just something to keep in mind going forward as you build your code. Thanks!
