### ISSUE TITLE
EarlyendpointD57 in make_table_all.R (cor tabular) breaking for ensemble

### ISSUE THREAD

**Issue by youyifong** [CoVPN/correlates_reporting#476]
@cyu-hvtn The error msg is copied below. 

Error: Problem with `mutate()` input `Case.D57`.
✖ object 'EarlyendpointD57' not found
ℹ Input `Case.D57` is `case_when(...)`.
Backtrace:
     █
  1. ├─`%>%`(...)
  2. ├─dplyr::mutate(...)
  3. ├─dplyr:::mutate.data.frame(...)
  4. │ └─dplyr:::mutate_cols(.data, ...)
  5. │   ├─base::withCallingHandlers(...)
  6. │   └─mask$eval_all_mutate(quo)
  7. ├─dplyr::case_when(...)
  8. │ └─rlang::eval_tidy(pair$lhs, env = default_env)
  9. └─base::.handleSimpleError(...)
 10.   └─dplyr:::h(simpleError(msg, call))
Execution halted
Makefile:6: recipe for target 'tables_output' failed

**Comment by youyifong** [comment]
By the way, on a separate note, I made this change in the same file to remove the warning that caught out eyes a few times (@benkeser @nhejazi )

#assays_col <- levels(interaction(visits, assays, sep="")) # interaction gives a warning about In ans * length(l) + if1 : longer object length is not a multiple of shorter object length
assays_col <- c(outer(visits, sort(assays), paste0)) # this reproduces the results from the previous line without the warning

**Comment by cyu-hvtn** [comment]
I noticed this too. Working on updating cor_tabular code for ensemble.

**Comment by youyifong** [comment]
@cyu-hvtn @yiwenlu Is there a PR that addressed this issue?

**Comment by cyu-hvtn** [comment]
Yes, included in #489

**Comment by youyifong** [comment]
Thanks!
