### ISSUE TITLE
clean_data error on real ensemble data (cop_mediation)

### ISSUE THREAD

**Issue by youyifong** [CoVPN/correlates_reporting#477]
@benkeser 

make[1]: Entering directory '/trials/covpn/p3003/analysis/correlates_reporting/cop_mediation'
Rscript code/clean_data.R
Warning message:
Project requested R version '4.1.0' but '4.0.4' is currently being used

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘kyotil’

The following object is masked from ‘package:dplyr’:

    last

Warning messages:
1: Project requested R version '4.1.0' but '4.0.4' is currently being used
2: In max(full_data[full_data$EventIndPrimaryD57 == 1 & full_data$Trt ==  :
  no non-missing arguments to max; returning -Inf
[1] "Day29"
Rscript code/run_analysis.R
Warning message:
Project requested R version '4.1.0' but '4.0.4' is currently being used

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘kyotil’

The following object is masked from ‘package:dplyr’:

    last

here() starts at /trials/covpn/p3003/analysis/correlates_reporting/cop_mediation
Loading required package: nnls
Loading required package: gam
Loading required package: splines
Loading required package: foreach
Loaded gam 1.20

Super Learner
Version: 2.0-28
Package created on 2021-05-04

Warning messages:
1: Project requested R version '4.1.0' but '4.0.4' is currently being used
2: In max(full_data[full_data$EventIndPrimaryD57 == 1 & full_data$Trt ==  :
  no non-missing arguments to max; returning -Inf
[1] "Day29bindSpike"
Loading required package: nloptr
Loading required namespace: glmnet
Loading required namespace: xgboost
Loading required namespace: ranger
Error in SuperLearner::SuperLearner(Y = Y[R == 1 & C == 1], X = data.frame(A = A,  :
  missing data is currently not supported. Check Y, X, and newX for missing values
Calls: natmed2 -> <Anonymous>
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Makefile:16: recipe for target 'output/full_result.rds' failed
make[1]: *** [output/full_result.rds] Error 1
make[1]: Target 'all' not remade because of errors.
make[1]: Leaving directory '/trials/covpn/p3003/analysis/correlates_reporting/cop_mediation'
Makefile:40: recipe for target 'cop_analysis' failed
make: *** [cop_analysis] Error 2

**Comment by benkeser** [comment]
The cop mediation analysis should be, for the time being, removed from the cor report build. We need to have a discussion based on immuno reports as to which, if any, assays will meet the assumptions of the method.

**Comment by youyifong** [comment]
Okay, I will close the issue.
