### ISSUE TITLE
Random Selection Reproducibility

### ISSUE THREAD

**Issue by thebioengineer** [CoVPN/correlates_reporting#48]
I wanted to open an issue to document how we wanted to approach reproducibility with respect to random selections. 
Normally I approach this by setting a seed  just before the random selection, but I wanted to solicit thoughts and feedback. 

This will be important for the verification of plots where we do random subsetting, possibly other scenarios as well.

@benkeser @nhejazi

**Comment by benkeser** [comment]
I think the moral of this story is that as long as the approach is described well enough in the specs, then there doesn't need to be a unified handling of it.

I'm going to close the issue for now; but can reopen if anyone has any more thoughts.
