### ISSUE TITLE
cor_graphical error

### ISSUE THREAD

**Issue by youyifong** [CoVPN/correlates_reporting#495]
@yiwenlu Could you take a look at this error on real ensemble data? 

make[1]: Entering directory '/trials/covpn/p3003/analysis/correlates_reporting/cor_graphical'
rm -f data_clean/* && rm -f output/*
Rscript code/cor_data_preprocess.R
Warning message:
Project requested R version '4.1.0' but '4.0.4' is currently being used

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘kyotil’

The following object is masked from ‘package:dplyr’:

    last

here() starts at /trials/covpn/p3003/analysis/correlates_reporting/cor_graphical
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──
✔ tibble  3.1.1     ✔ purrr   0.3.4
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ kyotil::last()  masks dplyr::last()
Error in `[[<-.data.frame`(`*tmp*`, t, value = logical(0)) :
  replacement has 0 rows, data has 1830
Calls: [[<- -> [[<-.data.frame
Execution halted
Makefile:6: recipe for target 'clean_data' failed
make[1]: *** [clean_data] Error 1
make[1]: Target 'all' not remade because of errors.
make[1]: Leaving directory '/trials/covpn/p3003/analysis/correlates_reporting/cor_graphical'
Makefile:20: recipe for target 'cor_analysis' failed
make: *** [cor_analysis] Error 2

**Comment by yiwenlu** [comment]
@youyifong I tested cor_data_preprocess.R with janssen_pooled_real_data_processed.csv but didn't get this error. Is this csv what you used for this run?

**Comment by youyifong** [comment]
I used the data with risk score that is under data_clean on cosrv.

**Comment by youyifong** [comment]
@yiwenlu I am also using janssen_pooled_real_data_processed.csv since risk score does to impact cor graphical. I think the problem comes from this line in data preprocess:


# assign values above the uloq to the uloq
for (t in c("B", if(has29) "Day29", "Day57") ) {
  dat.long.cor.subset[[t]] <- ifelse(dat.long.cor.subset[[t]] > dat.long.cor.subset$ULoQ, dat.long.cor.subset$ULoQ, dat.long.cor.subset[[t]])
}

**Comment by yiwenlu** [comment]
@youyifong I just submitted a PR for this issue.
