### ISSUE TITLE
move international unit conversion from data processing to data mapping

### ISSUE THREAD

**Issue by youyifong** [CoVPN/correlates_reporting#585]
@yiwenlu @youyifong

**Comment by youyifong** [comment]
@peterbriangilbert  Should we update the mock datasets as well to be on the international unit?

**Comment by yiwenlu** [comment]
I have changed units in the mapped dataset from log10(AU/mL) to log10(IU/mL) @youyifong

**Comment by youyifong** [comment]
thanks!
