### ISSUE TITLE
horizontal tables in immuno report

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#73]
When the immuno report is knitted to a pdf, some tables run off the page. 

Maybe [this solution](https://stackoverflow.com/questions/25849814/rstudio-rmarkdown-both-portrait-and-landscape-layout-in-a-single-pdf ) could help?

**Comment by benkeser** [comment]
Any updates on this?

**Comment by cyu-hvtn** [comment]
Still working on it. I missed some changes in the SAP that need to be addressed in my code. My estimation is to finish by tonight.

**Comment by benkeser** [comment]
@cyu-hvtn how's the progress coming? Anything we can do to help?
