### ISSUE TITLE
latex gore

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#78]
There is currently some latex gore in the `immuno` report.

<img width="677" alt="Screen Shot 2021-03-01 at 9 33 58 AM" src="https://user-images.githubusercontent.com/17482713/109511700-515eea00-7a71-11eb-8b64-a92b42c8d4e7.png">

**Comment by benkeser** [comment]
I found the source of this issue. If you have a `%` symbol in `fig.cap` it needs to be escaped as `\\%`. E.g., [here](https://github.com/CoVPN/correlates_reporting/blob/1961a31633eee3f34cb23558ad5605c93cf1dcc6/cor_coxph/report_sub.Rmd#L86)

Could I bother @yiwenlu or @KenLi93  to go ahead and fix in `report.Rmd` any figure with a % in the caption?

**Comment by KenLi93** [comment]
Hi David,

Thank you for identifying the issue!

Best regards,
Kendrick

**Comment by benkeser** [comment]
Resolved in #120
