### ISSUE TITLE
NA in plot

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#79]
@KenLi93 @yiwenlu 

This figure in the `immuno` report needs some tweaks. What's up with the `NA`? And the legend is cut off.

<img width="747" alt="Screen Shot 2021-03-01 at 9 36 31 AM" src="https://user-images.githubusercontent.com/17482713/109512107-bca8bc00-7a71-11eb-9602-e0c13c3f686b.png">

**Comment by benkeser** [comment]
@KenLi93 @yiwenlu  Any updates on this?

**Comment by yiwenlu** [comment]
Hi David,

Not yet. I’m checking this with Kendrick.

Yiwen

**Comment by KenLi93** [comment]
Hi David,

This problem was fixed in the recent pull requests.

Best regards,
Kendrick
