### ISSUE TITLE
threshold CI questions

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#87]
Why, when the risk dips to 0, does the CI go from 0 to 1? I also wonder whether it is possible to render the superscripts in math font?

<img width="546" alt="Screen Shot 2021-03-01 at 9 08 02 PM" src="https://user-images.githubusercontent.com/17482713/109585876-48eacb80-7ad2-11eb-8a65-7e6938f7d8cd.png">

_Originally posted by @benkeser in https://github.com/CoVPN/correlates_reporting/issues/85#issuecomment-788520231_

**Comment by nhejazi** [comment]
This seems resolved now that #85 has been merged. Closing but feel free to re-open if necessary.
