### ISSUE TITLE
Axis size in `cor_threshold`

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#88]
Minor detail, but the font size on the axes are a bit large. 

<img width="471" alt="Screen Shot 2021-03-01 at 9 10 45 PM" src="https://user-images.githubusercontent.com/17482713/109586086-a1ba6400-7ad2-11eb-802b-4c11c6babce1.png">

_Originally posted by @benkeser in https://github.com/CoVPN/correlates_reporting/issues/85#issuecomment-788520915_

**Comment by benkeser** [comment]
@Larsvanderlaan any update on this?

**Comment by Larsvanderlaan** [comment]
This should be fixed in the latest pull request #98. 
Thank you for your help!
