### ISSUE TITLE
`ylim` plotting error in `cor_coxph`

### ISSUE THREAD

**Issue by nhejazi** [CoVPN/correlates_reporting#97]
The automated Travis builds are running into an error due to non-finite `ylim` values in a call to `plot()`, in `cor_coxph` (https://travis-ci.com/github/CoVPN/correlates_reporting/builds/218921367#L2899). With a fresh clone from the `travis_fix` branch, are you able to replicate this @youyifong?

**Comment by youyifong** [comment]
I tried this but got an error:

yfong@volta:~/tmp$ git clone
https://github.com/CoVPN/correlates_reporting/tree/travis_fixes
Cloning into 'travis_fixes'...
fatal: repository '
https://github.com/CoVPN/correlates_reporting/tree/travis_fixes/' not found

Might have to do with credentials? I have a token, but not sure how to use
it from command line.

**Comment by youyifong** [comment]
I just did a fresh build:

make data_processed
then cor_coxph/make

using PR #99 and it worked.

Is your marginalizedRisk installed from CRAN or github
youyifong/marginalizedRisk ?

**Comment by nhejazi** [comment]
Excellent news re: #99, will merge if the Travis build is passing. It looks like the package version is installed from GitHub (https://github.com/CoVPN/correlates_reporting/blob/travis_fixes/renv.lock#L1055) so should be up to date.

**Comment by youyifong** [comment]
I got the error too with the travis branch.

**Comment by youyifong** [comment]
I figured it out. The error occured because when I set wt.2 to NA for the
subjects not in the population of interest, cor_coxph code broke. I fixed
it in cor_coxph, but at around the same time, my fork got detached. If PR99
and travis_fix can be merged, it should work.

**Comment by benkeser** [comment]
#99 has now been merged into #96. If build confirms, will merge into `master`.

**Comment by nhejazi** [comment]
Seems to be resolved in #96
